name: Generate Help

on:
  push:
    branches: [main]

jobs:
  generate-help:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: srcerite
          description: Neovim colorscheme inspired by Srcery 
          toc: false
          shiftheadinglevelby: -1
      - run: |
          git add doc/*.txt
          if git diff-index --quiet HEAD --; then
            : Nothing to commit
          else
            git commit -m "auto: generate help"
          fi
      - run: |
          git push
